using System.Collections.Generic;

namespace WebImageToAscii.Models
{
  /// <summary>
  /// Represents the luminance values for each ASCII character.
  /// </summary>
  public class Luminances
  {
    /// <summary>
    /// Stores Luminance values and respective ASCII characters.
    /// </summary>
    public List<Luminance> Configuration { get; set; }

    /// <summary>
    /// Default constructor.
    /// Initialises the lumanance list.
    /// </summary>
    public Luminances()
    {
    Initialise();
    }

    /// <summary>
    /// Stores 256 luminance values and their respective ASCII characters in a Luminance list, Configuration.
    /// The LuminanceValue is currently unused, but has been included both for readability and in case a future feature would require it.
    /// </summary>
    private void Initialise()
    {
      Configuration = new List<Luminance>
      {
        new Luminance { LuminanceValue = 0, CharValue = "@" },
        new Luminance { LuminanceValue = 1, CharValue = "@" },
        new Luminance { LuminanceValue = 2, CharValue = "@" },
        new Luminance { LuminanceValue = 3, CharValue = "@" },
        new Luminance { LuminanceValue = 4, CharValue = "@" },
        new Luminance { LuminanceValue = 5, CharValue = "@" },
        new Luminance { LuminanceValue = 6, CharValue = "@" },
        new Luminance { LuminanceValue = 7, CharValue = "@" },
        new Luminance { LuminanceValue = 8, CharValue = "@" },
        new Luminance { LuminanceValue = 9, CharValue = "@" },
        new Luminance { LuminanceValue = 10, CharValue = "@" },
        new Luminance { LuminanceValue = 11, CharValue = "@" },
        new Luminance { LuminanceValue = 12, CharValue = "@" },
        new Luminance { LuminanceValue = 13, CharValue = "@" },
        new Luminance { LuminanceValue = 14, CharValue = "@" },
        new Luminance { LuminanceValue = 15, CharValue = "@" },
        new Luminance { LuminanceValue = 16, CharValue = "@" },
        new Luminance { LuminanceValue = 17, CharValue = "@" },
        new Luminance { LuminanceValue = 18, CharValue = "@" },
        new Luminance { LuminanceValue = 19, CharValue = "@" },
        new Luminance { LuminanceValue = 20, CharValue = "@" },
        new Luminance { LuminanceValue = 21, CharValue = "@" },
        new Luminance { LuminanceValue = 22, CharValue = "Q" },
        new Luminance { LuminanceValue = 23, CharValue = "Q" },
        new Luminance { LuminanceValue = 24, CharValue = "Q" },
        new Luminance { LuminanceValue = 25, CharValue = "Q" },
        new Luminance { LuminanceValue = 26, CharValue = "Q" },
        new Luminance { LuminanceValue = 27, CharValue = "Q" },
        new Luminance { LuminanceValue = 28, CharValue = "Q" },
        new Luminance { LuminanceValue = 29, CharValue = "Q" },
        new Luminance { LuminanceValue = 30, CharValue = "Q" },
        new Luminance { LuminanceValue = 31, CharValue = "Q" },
        new Luminance { LuminanceValue = 32, CharValue = "Q" },
        new Luminance { LuminanceValue = 33, CharValue = "Q" },
        new Luminance { LuminanceValue = 34, CharValue = "Q" },
        new Luminance { LuminanceValue = 35, CharValue = "Q" },
        new Luminance { LuminanceValue = 36, CharValue = "Q" },
        new Luminance { LuminanceValue = 37, CharValue = "Q" },
        new Luminance { LuminanceValue = 38, CharValue = "Q" },
        new Luminance { LuminanceValue = 39, CharValue = "Q" },
        new Luminance { LuminanceValue = 40, CharValue = "Q" },
        new Luminance { LuminanceValue = 41, CharValue = "Q" },
        new Luminance { LuminanceValue = 42, CharValue = "Q" },
        new Luminance { LuminanceValue = 43, CharValue = "W" },
        new Luminance { LuminanceValue = 44, CharValue = "W" },
        new Luminance { LuminanceValue = 45, CharValue = "W" },
        new Luminance { LuminanceValue = 46, CharValue = "&" },
        new Luminance { LuminanceValue = 47, CharValue = "&" },
        new Luminance { LuminanceValue = 48, CharValue = "&" },
        new Luminance { LuminanceValue = 49, CharValue = "g" },
        new Luminance { LuminanceValue = 50, CharValue = "g" },
        new Luminance { LuminanceValue = 51, CharValue = "g" },
        new Luminance { LuminanceValue = 52, CharValue = "g" },
        new Luminance { LuminanceValue = 53, CharValue = "g" },
        new Luminance { LuminanceValue = 54, CharValue = "M" },
        new Luminance { LuminanceValue = 55, CharValue = "M" },
        new Luminance { LuminanceValue = 56, CharValue = "M" },
        new Luminance { LuminanceValue = 57, CharValue = "M" },
        new Luminance { LuminanceValue = 58, CharValue = "M" },
        new Luminance { LuminanceValue = 59, CharValue = "M" },
        new Luminance { LuminanceValue = 60, CharValue = "$" },
        new Luminance { LuminanceValue = 61, CharValue = "$" },
        new Luminance { LuminanceValue = 62, CharValue = "$" },
        new Luminance { LuminanceValue = 63, CharValue = "$" },
        new Luminance { LuminanceValue = 64, CharValue = "$" },
        new Luminance { LuminanceValue = 65, CharValue = "$" },
        new Luminance { LuminanceValue = 66, CharValue = "B" },
        new Luminance { LuminanceValue = 67, CharValue = "B" },
        new Luminance { LuminanceValue = 68, CharValue = "0" },
        new Luminance { LuminanceValue = 69, CharValue = "0" },
        new Luminance { LuminanceValue = 70, CharValue = "%" },
        new Luminance { LuminanceValue = 71, CharValue = "%" },
        new Luminance { LuminanceValue = 72, CharValue = "#" },
        new Luminance { LuminanceValue = 73, CharValue = "#" },
        new Luminance { LuminanceValue = 74, CharValue = "]" },
        new Luminance { LuminanceValue = 75, CharValue = "]" },
        new Luminance { LuminanceValue = 76, CharValue = "[" },
        new Luminance { LuminanceValue = 77, CharValue = "[" },
        new Luminance { LuminanceValue = 78, CharValue = "O" },
        new Luminance { LuminanceValue = 79, CharValue = "O" },
        new Luminance { LuminanceValue = 80, CharValue = "O" },
        new Luminance { LuminanceValue = 81, CharValue = "k" },
        new Luminance { LuminanceValue = 82, CharValue = "k" },
        new Luminance { LuminanceValue = 83, CharValue = "k" },
        new Luminance { LuminanceValue = 84, CharValue = "R" },
        new Luminance { LuminanceValue = 85, CharValue = "R" },
        new Luminance { LuminanceValue = 86, CharValue = "N" },
        new Luminance { LuminanceValue = 87, CharValue = "N" },
        new Luminance { LuminanceValue = 88, CharValue = "E" },
        new Luminance { LuminanceValue = 89, CharValue = "E" },
        new Luminance { LuminanceValue = 90, CharValue = "G" },
        new Luminance { LuminanceValue = 91, CharValue = "G" },
        new Luminance { LuminanceValue = 92, CharValue = "D" },
        new Luminance { LuminanceValue = 93, CharValue = "D" },
        new Luminance { LuminanceValue = 94, CharValue = "m" },
        new Luminance { LuminanceValue = 95, CharValue = "m" },
        new Luminance { LuminanceValue = 96, CharValue = "A" },
        new Luminance { LuminanceValue = 97, CharValue = "A" },
        new Luminance { LuminanceValue = 98, CharValue = "A" },
        new Luminance { LuminanceValue = 99, CharValue = "8" },
        new Luminance { LuminanceValue = 100, CharValue = "8" },
        new Luminance { LuminanceValue = 101, CharValue = "8" },
        new Luminance { LuminanceValue = 102, CharValue = "w" },
        new Luminance { LuminanceValue = 103, CharValue = "q" },
        new Luminance { LuminanceValue = 104, CharValue = "X" },
        new Luminance { LuminanceValue = 105, CharValue = "9" },
        new Luminance { LuminanceValue = 106, CharValue = "6" },
        new Luminance { LuminanceValue = 107, CharValue = "5" },
        new Luminance { LuminanceValue = 108, CharValue = "l" },
        new Luminance { LuminanceValue = 109, CharValue = "e" },
        new Luminance { LuminanceValue = 110, CharValue = "b" },
        new Luminance { LuminanceValue = 111, CharValue = "I" },
        new Luminance { LuminanceValue = 112, CharValue = "F" },
        new Luminance { LuminanceValue = 113, CharValue = "4" },
        new Luminance { LuminanceValue = 114, CharValue = "V" },
        new Luminance { LuminanceValue = 115, CharValue = "V" },
        new Luminance { LuminanceValue = 116, CharValue = "V" },
        new Luminance { LuminanceValue = 117, CharValue = "P" },
        new Luminance { LuminanceValue = 118, CharValue = "P" },
        new Luminance { LuminanceValue = 119, CharValue = "P" },
        new Luminance { LuminanceValue = 120, CharValue = "U" },
        new Luminance { LuminanceValue = 121, CharValue = "S" },
        new Luminance { LuminanceValue = 122, CharValue = "K" },
        new Luminance { LuminanceValue = 123, CharValue = "H" },
        new Luminance { LuminanceValue = 124, CharValue = "3" },
        new Luminance { LuminanceValue = 125, CharValue = "2" },
        new Luminance { LuminanceValue = 126, CharValue = "Y" },
        new Luminance { LuminanceValue = 127, CharValue = "Y" },
        new Luminance { LuminanceValue = 128, CharValue = "T" },
        new Luminance { LuminanceValue = 129, CharValue = "T" },
        new Luminance { LuminanceValue = 130, CharValue = "y" },
        new Luminance { LuminanceValue = 131, CharValue = "x" },
        new Luminance { LuminanceValue = 132, CharValue = "s" },
        new Luminance { LuminanceValue = 133, CharValue = "h" },
        new Luminance { LuminanceValue = 134, CharValue = "Z" },
        new Luminance { LuminanceValue = 135, CharValue = "Z" },
        new Luminance { LuminanceValue = 136, CharValue = "C" },
        new Luminance { LuminanceValue = 137, CharValue = "f" },
        new Luminance { LuminanceValue = 138, CharValue = "f" },
        new Luminance { LuminanceValue = 139, CharValue = "f" },
        new Luminance { LuminanceValue = 140, CharValue = "f" },
        new Luminance { LuminanceValue = 141, CharValue = "f" },
        new Luminance { LuminanceValue = 142, CharValue = "f" },
        new Luminance { LuminanceValue = 143, CharValue = "}" },
        new Luminance { LuminanceValue = 144, CharValue = "{" },
        new Luminance { LuminanceValue = 145, CharValue = "u" },
        new Luminance { LuminanceValue = 146, CharValue = "7" },
        new Luminance { LuminanceValue = 147, CharValue = "(" },
        new Luminance { LuminanceValue = 148, CharValue = ")" },
        new Luminance { LuminanceValue = 149, CharValue = "r" },
        new Luminance { LuminanceValue = 150, CharValue = "n" },
        new Luminance { LuminanceValue = 151, CharValue = "J" },
        new Luminance { LuminanceValue = 152, CharValue = "?" },
        new Luminance { LuminanceValue = 153, CharValue = "1" },
        new Luminance { LuminanceValue = 154, CharValue = "!" },
        new Luminance { LuminanceValue = 155, CharValue = "z" },
        new Luminance { LuminanceValue = 156, CharValue = "z" },
        new Luminance { LuminanceValue = 157, CharValue = "/" },
        new Luminance { LuminanceValue = 158, CharValue = "/" },
        new Luminance { LuminanceValue = 159, CharValue = "+" },
        new Luminance { LuminanceValue = 160, CharValue = "+" },
        new Luminance { LuminanceValue = 161, CharValue = "v" },
        new Luminance { LuminanceValue = 162, CharValue = "v" },
        new Luminance { LuminanceValue = 163, CharValue = "v" },
        new Luminance { LuminanceValue = 164, CharValue = "c" },
        new Luminance { LuminanceValue = 165, CharValue = "c" },
        new Luminance { LuminanceValue = 166, CharValue = "c" },
        new Luminance { LuminanceValue = 167, CharValue = "~" },
        new Luminance { LuminanceValue = 168, CharValue = "~" },
        new Luminance { LuminanceValue = 169, CharValue = "\\" },
        new Luminance { LuminanceValue = 170, CharValue = "\\" },
        new Luminance { LuminanceValue = 171, CharValue = "*" },
        new Luminance { LuminanceValue = 172, CharValue = "*" },
        new Luminance { LuminanceValue = 173, CharValue = "L" },
        new Luminance { LuminanceValue = 174, CharValue = "L" },
        new Luminance { LuminanceValue = 175, CharValue = "L" },
        new Luminance { LuminanceValue = 176, CharValue = ">" },
        new Luminance { LuminanceValue = 177, CharValue = ">" },
        new Luminance { LuminanceValue = 178, CharValue = ">" },
        new Luminance { LuminanceValue = 179, CharValue = "=" },
        new Luminance { LuminanceValue = 180, CharValue = "=" },
        new Luminance { LuminanceValue = 181, CharValue = "=" },
        new Luminance { LuminanceValue = 182, CharValue = "<" },
        new Luminance { LuminanceValue = 183, CharValue = "<" },
        new Luminance { LuminanceValue = 184, CharValue = "<" },
        new Luminance { LuminanceValue = 185, CharValue = ";" },
        new Luminance { LuminanceValue = 186, CharValue = ";" },
        new Luminance { LuminanceValue = 187, CharValue = ";" },
        new Luminance { LuminanceValue = 188, CharValue = ";" },
        new Luminance { LuminanceValue = 189, CharValue = ";" },
        new Luminance { LuminanceValue = 190, CharValue = ";" },
        new Luminance { LuminanceValue = 191, CharValue = "^" },
        new Luminance { LuminanceValue = 192, CharValue = "^" },
        new Luminance { LuminanceValue = 193, CharValue = "^" },
        new Luminance { LuminanceValue = 194, CharValue = "^" },
        new Luminance { LuminanceValue = 195, CharValue = "^" },
        new Luminance { LuminanceValue = 196, CharValue = "^" },
        new Luminance { LuminanceValue = 197, CharValue = "^" },
        new Luminance { LuminanceValue = 198, CharValue = "^" },
        new Luminance { LuminanceValue = 199, CharValue = "^" },
        new Luminance { LuminanceValue = 200, CharValue = "^" },
        new Luminance { LuminanceValue = 201, CharValue = "^" },
        new Luminance { LuminanceValue = 202, CharValue = "_" },
        new Luminance { LuminanceValue = 203, CharValue = "_" },
        new Luminance { LuminanceValue = 204, CharValue = "_" },
        new Luminance { LuminanceValue = 205, CharValue = ":" },
        new Luminance { LuminanceValue = 206, CharValue = ":" },
        new Luminance { LuminanceValue = 207, CharValue = ":" },
        new Luminance { LuminanceValue = 208, CharValue = "," },
        new Luminance { LuminanceValue = 209, CharValue = "," },
        new Luminance { LuminanceValue = 210, CharValue = "," },
        new Luminance { LuminanceValue = 211, CharValue = "," },
        new Luminance { LuminanceValue = 212, CharValue = "," },
        new Luminance { LuminanceValue = 213, CharValue = "," },
        new Luminance { LuminanceValue = 214, CharValue = "\"" },
        new Luminance { LuminanceValue = 215, CharValue = "\"" },
        new Luminance { LuminanceValue = 216, CharValue = "\"" },
        new Luminance { LuminanceValue = 217, CharValue = "'" },
        new Luminance { LuminanceValue = 218, CharValue = "'" },
        new Luminance { LuminanceValue = 219, CharValue = "'" },
        new Luminance { LuminanceValue = 220, CharValue = "`" },
        new Luminance { LuminanceValue = 221, CharValue = "`" },
        new Luminance { LuminanceValue = 222, CharValue = "`" },
        new Luminance { LuminanceValue = 223, CharValue = "`" },
        new Luminance { LuminanceValue = 224, CharValue = "`" },
        new Luminance { LuminanceValue = 225, CharValue = "`" },
        new Luminance { LuminanceValue = 226, CharValue = "." },
        new Luminance { LuminanceValue = 227, CharValue = "." },
        new Luminance { LuminanceValue = 228, CharValue = "." },
        new Luminance { LuminanceValue = 229, CharValue = "-" },
        new Luminance { LuminanceValue = 230, CharValue = "-" },
        new Luminance { LuminanceValue = 231, CharValue = "-" },
        new Luminance { LuminanceValue = 232, CharValue = " " },
        new Luminance { LuminanceValue = 233, CharValue = " " },
        new Luminance { LuminanceValue = 234, CharValue = " " },
        new Luminance { LuminanceValue = 235, CharValue = " " },
        new Luminance { LuminanceValue = 236, CharValue = " " },
        new Luminance { LuminanceValue = 237, CharValue = " " },
        new Luminance { LuminanceValue = 238, CharValue = " " },
        new Luminance { LuminanceValue = 239, CharValue = " " },
        new Luminance { LuminanceValue = 240, CharValue = " " },
        new Luminance { LuminanceValue = 241, CharValue = " " },
        new Luminance { LuminanceValue = 242, CharValue = " " },
        new Luminance { LuminanceValue = 243, CharValue = " " },
        new Luminance { LuminanceValue = 244, CharValue = " " },
        new Luminance { LuminanceValue = 245, CharValue = " " },
        new Luminance { LuminanceValue = 246, CharValue = " " },
        new Luminance { LuminanceValue = 247, CharValue = " " },
        new Luminance { LuminanceValue = 248, CharValue = " " },
        new Luminance { LuminanceValue = 249, CharValue = " " },
        new Luminance { LuminanceValue = 250, CharValue = " " },
        new Luminance { LuminanceValue = 251, CharValue = " " },
        new Luminance { LuminanceValue = 252, CharValue = " " },
        new Luminance { LuminanceValue = 253, CharValue = " " },
        new Luminance { LuminanceValue = 254, CharValue = " " },
        new Luminance { LuminanceValue = 255, CharValue = " " },
      };           
    }
  }
}